FROM ubuntu:24.04

RUN apt -y update && apt install -y \
    build-essential \ 
    pkg-config \  
    libssl-dev \
    python3 \
    python3-pip \
    git \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app/

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

RUN curl -LsSf https://astral.sh/uv/install.sh | sh
RUN uv venv && . /app/.venv/bin/activate && uv pip install pre-commit
